name: Run Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]  # Adjust as needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Compile requirements.txt
      run: |
        uv pip compile pyproject.toml --output-file requirements.txt

    - name: Install dependencies
      run: |
        uv pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests
